//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        internal static string Accommodation {
            get {
                return ResourceManager.GetString("Accommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation name.
        /// </summary>
        internal static string Accommodation_name {
            get {
                return ResourceManager.GetString("Accommodation name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation view.
        /// </summary>
        internal static string Accommodation_view {
            get {
                return ResourceManager.GetString("Accommodation view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acommodation and owner rating.
        /// </summary>
        internal static string Acommodation_and_owner_rating {
            get {
                return ResourceManager.GetString("Acommodation and owner rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acommodation renovation suggestion.
        /// </summary>
        internal static string Acommodation_renovation_suggestion {
            get {
                return ResourceManager.GetString("Acommodation renovation suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available days.
        /// </summary>
        internal static string Available_days {
            get {
                return ResourceManager.GetString("Available days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel in advance:.
        /// </summary>
        internal static string Cancel_in_advance_ {
            get {
                return ResourceManager.GetString("Cancel in advance:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        internal static string Cancel_reservation {
            get {
                return ResourceManager.GetString("Cancel reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant find what you are looking for? Create forum.
        /// </summary>
        internal static string Cant_find_what_you_are_looking_for__Create_forum {
            get {
                return ResourceManager.GetString("Cant find what you are looking for? Create forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out reviews from owners.
        /// </summary>
        internal static string Check_out_reviews_from_owners {
            get {
                return ResourceManager.GetString("Check out reviews from owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string City_ {
            get {
                return ResourceManager.GetString("City:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleannes.
        /// </summary>
        internal static string Cleannes {
            get {
                return ResourceManager.GetString("Cleannes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanness.
        /// </summary>
        internal static string Cleanness {
            get {
                return ResourceManager.GetString("Cleanness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close forum.
        /// </summary>
        internal static string Close_forum {
            get {
                return ResourceManager.GetString("Close forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create forum.
        /// </summary>
        internal static string Create_forum {
            get {
                return ResourceManager.GetString("Create forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating reservation.
        /// </summary>
        internal static string Creating_reservation {
            get {
                return ResourceManager.GetString("Creating reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        internal static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string End_date {
            get {
                return ResourceManager.GetString("End date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter image url.
        /// </summary>
        internal static string Enter_image_url {
            get {
                return ResourceManager.GetString("Enter image url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number of guests.
        /// </summary>
        internal static string Enter_number_of_guests {
            get {
                return ResourceManager.GetString("Enter number of guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reservation days.
        /// </summary>
        internal static string Enter_reservation_days {
            get {
                return ResourceManager.GetString("Enter reservation days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your comment.
        /// </summary>
        internal static string Enter_your_comment {
            get {
                return ResourceManager.GetString("Enter your comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find reservation.
        /// </summary>
        internal static string Find_reservation {
            get {
                return ResourceManager.GetString("Find reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following Rules.
        /// </summary>
        internal static string Following_Rules {
            get {
                return ResourceManager.GetString("Following Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate report.
        /// </summary>
        internal static string Generate_report {
            get {
                return ResourceManager.GetString("Generate report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How urgent is this change?.
        /// </summary>
        internal static string How_urgent_is_this_change_ {
            get {
                return ResourceManager.GetString("How urgent is this change?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image view.
        /// </summary>
        internal static string Image_view {
            get {
                return ResourceManager.GetString("Image view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment.
        /// </summary>
        internal static string Leave_a_comment {
            get {
                return ResourceManager.GetString("Leave a comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review.
        /// </summary>
        internal static string Leave_a_review {
            get {
                return ResourceManager.GetString("Leave a review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review on your past reservations!.
        /// </summary>
        internal static string Leave_a_review_on_your_past_reservations_ {
            get {
                return ResourceManager.GetString("Leave a review on your past reservations!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 - Not necessary.
        /// </summary>
        internal static string Level_1___Not_necessary {
            get {
                return ResourceManager.GetString("Level 1 - Not necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 2 - Minor changes.
        /// </summary>
        internal static string Level_2___Minor_changes {
            get {
                return ResourceManager.GetString("Level 2 - Minor changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 3 - Bothersome things.
        /// </summary>
        internal static string Level_3___Bothersome_things {
            get {
                return ResourceManager.GetString("Level 3 - Bothersome things", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 4 - Really necessary.
        /// </summary>
        internal static string Level_4___Really_necessary {
            get {
                return ResourceManager.GetString("Level 4 - Really necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 5 - Really bad condition.
        /// </summary>
        internal static string Level_5___Really_bad_condition {
            get {
                return ResourceManager.GetString("Level 5 - Really bad condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max guests.
        /// </summary>
        internal static string Max_guests {
            get {
                return ResourceManager.GetString("Max guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max guests:.
        /// </summary>
        internal static string Max_guests_ {
            get {
                return ResourceManager.GetString("Max guests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min days of reservation.
        /// </summary>
        internal static string Min_days_of_reservation {
            get {
                return ResourceManager.GetString("Min days of reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min days of reservation:.
        /// </summary>
        internal static string Min_days_of_reservation_ {
            get {
                return ResourceManager.GetString("Min days of reservation:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        internal static string My_reservations {
            get {
                return ResourceManager.GetString("My reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        internal static string Noise {
            get {
                return ResourceManager.GetString("Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests.
        /// </summary>
        internal static string Number_of_guests {
            get {
                return ResourceManager.GetString("Number of guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner corectness.
        /// </summary>
        internal static string Owner_corectness {
            get {
                return ResourceManager.GetString("Owner corectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner name.
        /// </summary>
        internal static string Owner_name {
            get {
                return ResourceManager.GetString("Owner name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner reviews.
        /// </summary>
        internal static string Owner_reviews {
            get {
                return ResourceManager.GetString("Owner reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpone resevation.
        /// </summary>
        internal static string Postpone_resevation {
            get {
                return ResourceManager.GetString("Postpone resevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate owner.
        /// </summary>
        internal static string Rate_owner {
            get {
                return ResourceManager.GetString("Rate owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        internal static string Read_more {
            get {
                return ResourceManager.GetString("Read more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovation Suggestion.
        /// </summary>
        internal static string Renovation_Suggestion {
            get {
                return ResourceManager.GetString("Renovation Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenovationSuggestions.
        /// </summary>
        internal static string Renovation_Suggestions {
            get {
                return ResourceManager.GetString("Renovation Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation days.
        /// </summary>
        internal static string Reservation_days {
            get {
                return ResourceManager.GetString("Reservation days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation postponation.
        /// </summary>
        internal static string Reservation_postponation {
            get {
                return ResourceManager.GetString("Reservation postponation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        internal static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        internal static string Select_city {
            get {
                return ResourceManager.GetString("Select city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number.
        /// </summary>
        internal static string Select_number {
            get {
                return ResourceManager.GetString("Select number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select owner corectness.
        /// </summary>
        internal static string Select_owner_corectness {
            get {
                return ResourceManager.GetString("Select owner corectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select state.
        /// </summary>
        internal static string Select_state {
            get {
                return ResourceManager.GetString("Select state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select timeliness.
        /// </summary>
        internal static string Select_timeliness {
            get {
                return ResourceManager.GetString("Select timeliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type.
        /// </summary>
        internal static string Select_type {
            get {
                return ResourceManager.GetString("Select type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string Start_date {
            get {
                return ResourceManager.GetString("Start date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string State_ {
            get {
                return ResourceManager.GetString("State:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeliness.
        /// </summary>
        internal static string Timeliness {
            get {
                return ResourceManager.GetString("Timeliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Type_ {
            get {
                return ResourceManager.GetString("Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should we change?.
        /// </summary>
        internal static string What_should_we_change_ {
            get {
                return ResourceManager.GetString("What should we change?", resourceCulture);
            }
        }
    }
}
